# COMP 4050 Meeting Minutes
## 01/22
Members 
- John Manning
- Colton Dietterle
- Conner Kulbaski
- Gin (Meng Ching) Chiang

### Agenda:
1. Choose a leader
2. Discuss concepts for project
3. Choose team/project name
4. Hand in group names to TA

Project Concepts 
- Web application 
> - Using React for front end 
>> - Easy to learn, powerful
Brainstorm list - 
> Search algorithms visualizer
> ** 2 (or more!?) player web games (chess, etc.)
> Video Stream, live stream
> Audio visualizer
> Calendar app


Decided on a multiplayer game hosted on a web app, leaning towards a chess style turn based game to minimize latency issues and focus on the app development. 

TODO: This weekend - research frameworks/api’s or techniques for doing this, maybe also think about the game we will host. (either a pre made game like chess or a simple game like slither/pong)

Team name: Team n, n ∈ ℤ+

Decided on John as leader, John will email about voiding the 2% grade bonus. 


## 01/25
### Agenda:

1. Decide on game
2. Decide on Tech Stack.

Results of Meeting
* Tech Stack discussion
> * We decided on Next.js as our javascript framework.
> * Colton is looking into what that means for frontend/backend architecture
> * We will use google-trends-api - npm as the  API for the game data.
* Game outline finalised
> * We discussed making a lichess style website, an arcade game like pong or joust, a beer pong simulator, and party games like jackbox. 
> * We decided we are making a google search poker party game.
> * Inspired by The Higher Lower Game, the game works a bit like war. Each player is given a set of cards with various google search terms. They choose whichever one they think is the most searched, and bet “points” based on how sure they are that their card will be the highest. After everyone has played, the cards are revealed and the person with the highest searches wins the pot. 
* Decided on name for game
> * We are calling it SEO-ker
* Github repo created
> * We have agreed on some standards for merge and pull requests.
>> * Nobody accepts their own pull requests, they must be subject to code reviews by another team member.
>> * We merge the origin into the local branch, then the local branch back into the origin. 
>> * Each feature is a new branch.
> * We created the README, and added some descriptions of the project. 
* Next Time - Gin and John are working on the Documentation, setting up the files and writing more readme.
* Conner is looking up the API documentation, and Colton is looking into Next.js
* Meeting on Friday to start the user stories

## 01/31
### Agenda:
* Game Rules first draft
* Core Features
* User Stories
* Determine Stakeholders


_Game Rule_

Discussed Conner’s rules for the game, and all agreed that they look good. 

Decided MongoDB as SEO-ker's database

Core features:

Discussed features, decided on
1. User Profiles
2. Host and join private multiplayer lobbies via 6 digit code / invite link
3. Playing the game. 

Rubric says 3 features, Proposal says four, so we came up with a fourth, just in case. 

4. Integrate with google search API


Decide on user stories
```
a = Acceptance Test 
b = Priority 
c = Cost (Estimated with short, medium, long) *Completed on the 02/01 meeting*
```
**Feature 1**
1. As a user, I want to be able to create a user profile with a username and password, so that I can have my game statistics and information stored.
> a. I am able to login with my profile <br>
> b. Medium priority <br>
> c. Long

2. As a user, I want the application to remember me so I can get into a game quickly.
> a. I am able to join a game quickly <br>
> b. Low priority <br>
> c. Medium

3. As a user, I want to be able to upload a profile picture to flex my beauty
> a. I am able to see my beautiful profile picture when uploaded <br>
> b. Low priority <br>
> c. Medium

4. As a user, I want the game to differentiate me from other players in the game, so I know who is who. 
> a. I am able to tell accurately who is who <br>
> b. High priority <br>
> c. Short

**Feature 2**
1. As a user, I want to be able to host a multiplayer lobby so I can play with my friends. 
> a. I am able to host a game <br>
> b. High priority <br>
> c. Long

2. As a user, I want to be able to join a multiplayer lobby so I can play with my friends. 
> a. I am able to join a game <br>
> b. High priority <br>
> c. Medium

3. As a user, I want the game to generate a code so I can invite my friends easily. 
> a. I am able to distribute a code generated by the game <br>
> b. High priority <br>
> c. Short

4. As a host, I want to be able to reset the lobby so I can quickly play another game without sending out fresh invites.
> a. I am able to quickly play another game without sending new invites <br>
> b. Low Priority <br>
> c. Short - Medium

**Feature 3**
1. As a player, I expect the game to have well defined rules, so I am not surprised by mechanics
> a. I am able to play the game as expected by the rules defined <br>
> b. High priority <br>
> c. Long
2. As a player, I expect to have the rules explained to me, so I know how to play
> a. I am able to read the rules before or while playing the game <br>
> b. Low priority <br>
> c. Short
3. As a player, I want to be able to set a custom bet, so I can bluff and trick my friends
> a. I am able to set a custom bet that is within the amount of points I have <br>
> b. Medium Priority <br>
> c. Short
4. As a player, I want an interactive UI so that I can easily interact with the game. 
> a. I am able to navigate through the game without issues <br>
> b. Medium Priority <br>
> c. Long
5. As a player, I want to be able to play cards so that the game works as intended. 
> a. I am able to play cards <br>
> b. High Priority <br>
> c. Medium
6. As a player, I want to know how many chips I have, so I can make judgement calls.
> a. The number of chips I have is displayed and accurate <br>
> b. Medium <br>
> c. Short
7. As a player, I want to know how many chips others have and how much they are betting, so I can guess if they are bluffing or not. 
> a. The number of chips others have is displayed and accurate <br>
> b. Medium <br>
> c. Short
8. As a player, I want the game to end so I have time to do the dishes.
> a. The game ends when the game finishes <br>
> b. Medium <br>
> c. Short

**Feature 4**
1. As a player, I want the search statistics to be accurate and relevant, so I can make informed guesses on the value of my cards.
> a. Searching the result on Google API should give about the same result <br>
> b. High <br>
> c. Medium

**Stakeholders**
> The TA <br>
> Ourselves (Developers) <br>
> Folks who will play the game


**Next meeting**
```
Colton will add to readme doc - technologies 
Gin will update meeting minutes in wiki
John will clean up the readme wording
Conner will add the rules to the wiki 
We will discuss time estimates for user stories and finish the proposal document. 
```
## 02/01
### Agenda: 
- User Stories (Cost)

Time Cost is updated in the previous meeting. 


Assigned Gin to ask questions in Tanbir Ahmed's session about what we need to submit 
- Submit only Project proposal 
- Due date meeting on Wednesday? Or Friday? Sent an email but never got a reply.
- Clarify the point deduction for members not having commits, (for first sprint)

